apiVersion: skaffold/v1
kind: Config
metadata:
  name: get-analysis-id
deploy:
  kubectl:
    manifests:
    - k8s/get-analysis-id.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: discoenv/get-analysis-id
  local: {}
